# Generated by Django 2.0.5 on 2018-06-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=200)),
                ('sLogo', models.FileField(blank=True, upload_to='')),
                ('sCategory', models.ManyToManyField(to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetNumber', models.IntegerField()),
                ('streetName', models.CharField(max_length=250)),
                ('postalCode', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('locationCity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.City')),
                ('parentStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
