# Generated by Django 2.0.5 on 2018-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180720_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelocation',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
