# Generated by Django 2.0.5 on 2018-07-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180720_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='sLogo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
