# Generated by Django 2.0.5 on 2018-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180727_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sLogoURL',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
