# Generated by Django 2.0.5 on 2018-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_slogourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelocation',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='storelocation',
            name='streetNumber',
        ),
        migrations.AddField(
            model_name='storelocation',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
