# Generated by Django 2.0.5 on 2018-06-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='displayImage',
        ),
    ]
