# Generated by Django 2.0.5 on 2018-06-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productphoto_displayimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displayPic',
            field=models.ImageField(blank=True, upload_to='displayPictures'),
        ),
    ]
