# Generated by Django 2.0.5 on 2018-07-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='s',
            field=models.SlugField(blank=True, max_length=1000),
        ),
    ]
