# Generated by Django 2.0.5 on 2018-07-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='s',
            new_name='slug',
        ),
    ]
