# Generated by Django 2.0.5 on 2018-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180630_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='imageName',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='generalPictures'),
        ),
    ]
