# Generated by Django 2.0.5 on 2018-07-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('products', '0011_auto_20180701_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('regularPrice', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('salePrice', models.FloatField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('storeLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreLocation')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size4', models.IntegerField(default=0)),
                ('size4_5', models.IntegerField(default=0)),
                ('size5', models.IntegerField(default=0)),
                ('size5_5', models.IntegerField(default=0)),
                ('size6', models.IntegerField(default=0)),
                ('size6_5', models.IntegerField(default=0)),
                ('size7', models.IntegerField(default=0)),
                ('size7_5', models.IntegerField(default=0)),
                ('size8', models.IntegerField(default=0)),
                ('size8_5', models.IntegerField(default=0)),
                ('size9', models.IntegerField(default=0)),
                ('size9_5', models.IntegerField(default=0)),
                ('size10', models.IntegerField(default=0)),
                ('size10_5', models.IntegerField(default=0)),
                ('size11', models.IntegerField(default=0)),
                ('size11_5', models.IntegerField(default=0)),
                ('size12', models.IntegerField(default=0)),
                ('size12_5', models.IntegerField(default=0)),
                ('size13', models.IntegerField(default=0)),
                ('size13_5', models.IntegerField(default=0)),
                ('size14', models.IntegerField(default=0)),
                ('regularPrice', models.FloatField()),
                ('sale', models.BooleanField(default=False)),
                ('salesPrice', models.FloatField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('storeLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreLocation')),
            ],
        ),
    ]
