# Generated by Django 2.0.5 on 2018-07-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_storeinventory_storeinventory2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventory2',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storeinventory2',
            name='storeLocation',
        ),
        migrations.DeleteModel(
            name='StoreInventory2',
        ),
    ]
