# Generated by Django 2.0.5 on 2018-07-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180702_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='salePrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
