# Generated by Django 2.0.5 on 2018-07-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180708_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='size',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
