# Generated by Django 2.0.5 on 2018-07-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20180708_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='regularPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
